import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {NextIntlClientProvider} from 'next-intl';
import '@/styles/globals.css';
import { getMessages } from "next-intl/server";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "HealthCare - MediPro",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: {
    locale: 'vi' | 'en';
  }
} 

const RootLayout: React.FC<Props> = async ({
  children,
  params: {locale},     
}) => {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`font-sans ${fontSans.variable }`}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export default RootLayout;
